### ISSUE TITLE
Cargo not updated

### ISSUE THREAD

**Issue by kudla188** [nlhans/ets2-sdk-plugin#16] opened 2015-08-18 18:52 UTC
Cargo is still in memory when finished. Only TrailerAttached is set to false. Cargo destination should be null when i finish delivery.

**Comment by jammerxd** [comment] 2015-08-27 01:32
I cannot get my cargo to show up, even in the demo it is blank and won't update. Any ideas?

**Comment by leedonald54** [comment] 2015-08-29 20:56
What OS are you using  , sorry for asking , it will help , in long run ?

**Comment by nlhans** [comment] 2015-08-29 20:59
Jammerxd; make sure you're running the latest ETS2 version that supports the ETS 1.5 SDK

Cargo is indeed not reset upon delivery. However, TrailerAttached being set to false is not a valid delivery event. I will try to look into this if SCS has added any info event when a job is completed or aborted.

**Comment by leedonald54** [comment] 2015-08-29 21:09
The reason I asked as I am running Win 10 . In the last , about they came out and missed my game up bad , we are checking now . My HP G60 Will not up date to it , It did go on AMD tower .

**Comment by jammerxd** [comment] 2015-08-29 22:26
I am running Windows 10 pro x64 and the latest version of ETS2(1.19, not the beta 1.20). The cargo field simply remains blank and will not update at all.

**Comment by leedonald54** [comment] 2015-08-29 23:32
If you updated to verision 10532 , there is a meager problem , I tried playing yesterday & I did not have any loads showing and no way to play , it might be the up dates . As we get them at different times. They are two parts to this download  , please let me know. As I have connected Microsoft 10 team .

**Comment by leedonald54** [comment] 2015-08-30 00:38
Also If you got that cheek some other places . Was watching Windiws on tower , we may have to go Eterprise  , as it will support Legaccy & other option, has to do with Explore 11 , my lap top will not go be on 32% on first & restore to last , will check and see if Eurot Truck 2 will play , should tell us more .

**Comment by nlhans** [comment] 2015-08-30 07:48
Are other telemetry fields working? If so, is the truck model shown correctly?

I cannot imagine Windows 10 would interrupt in particular the cargo data fields. I unfortunately do not have a Windows 10 machine to test.

**Comment by jammerxd** [comment] 2015-08-30 08:00
Yes the trailerid, trailer, city destination and all other fields read back correctly, the cargo field is also blank when running window 7 and older versions of the telemetry dll and client. This may be an issue with the sdk as I saw the cargoid  was deprecated.

**Comment by kudla188** [comment] 2015-08-30 08:46
Cargo field issue: I have Win 10 Pro 64-bit on my machine and cargo field working correctly. So yeah, i think it's not about os. And... running game at ver. 1.19 (modified by ETS2MP). 

Cargo not updated issue: Now at the moment i checking if is distance left at 0 and trailer attached is false.

**Comment by jammerxd** [comment] 2015-08-30 14:29
So then what should I do to find out what my issue is?

**Comment by leedonald54** [comment] 2015-08-30 16:04
Could you tell me the version of Win 10 you are using was able to get part of mine fixed last night , it would help , I am still having with last build on lap top, it is a HPG60 535DX  have to work on it now , we at least a month be for the finally release as they push it back on Friday the 28 .

**Comment by leedonald54** [comment] 2015-08-30 16:07
I hope I can help in pinning it down, let me . As I will be gone this morning to church for 2 hours .

**Comment by kudla188** [comment] 2015-08-30 17:15
I have version 10.0.10240.

**Comment by leedonald54** [comment] 2015-08-31 09:09
That was a month ago we are on10525 & trying yo get 10535 , did not put 10 in front .Microsoft a month a go had both computers , 9: AM till 3:30 PM with that build & pulled a lot of information off , I have worked with Microsoft for15 years & BATA tested over 4 times . I know part of the problem is that the same INTELSAT video card was used onVista ,all 7 & 8,'8.1. And has PhysX in it . Have to get speasal help , will take some time , it v 2.18 & they stopped support for it on2.15 . I do know that Microsoft web cam 3000 will not work on Win 10. I will have to get just a 1080p or I any way. All I can say is I build high end AMD computers . I got some updates a couple hours as the computer came on . Will cheek in a bit..Sorry I kept thinking what might be blocking , as it took off the pictures off the bottom , were you log in also,both side'es, there is more there that is not right, I could make a new profile and I would get freest , but no pitchers or log in to pages.will hit back to you in bit.am housing a  gin I-pad my aid gave me .

**Comment by nlhans** [comment] 2015-09-15 18:58
Both issues should be fixed in version 1.4.0 which is now released.

The cargo field not updating is because it was reading from a memory field that was deprecated. The cargo field now contains the same contents as trailer name.
Job data is now cleared with the constraints described by kudla188; when the trailer attached flag goes to FALSE while the navigation distance is 0.0f. This seems to work reasonably well, however I couldn't find a proper job event in the SDK.

**Closed** 2015-11-16 22:09 UTC
Labels: bug, enhancement
